const USER_LOGIN = "USER_LOGIN"
const USER_LOGOUT = "USER_LOGOUT"

const USERS_ADD = "USERS_ADD"
const USERS_REMOVE = "USERS_REMOVE"

const c = "PEREVERZEVA_REACT_RGR"

export { USERS_REMOVE, USERS_ADD, USER_LOGIN, USER_LOGOUT, c }
